import Head from "next/head";

import styles from "./index.module.css";
import { api } from "~/utils/api";

export default function Home() {
  const testData = api.example.getTest.useQuery();

  if (testData.isError || testData.isLoading) {
    return;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Data from endpoint</h2>
        <h3>{testData.data.test}</h3>
      </main>
    </>
  );
}
